version: '3.8'

services:
  chapar-client:
    image: alpine:latest
    network_mode: "host"
    volumes:
      - ./chapar-client-linux-amd64:/app/chapar-client:ro
      - ./client_config.json:/app/client_config.json:ro
    entrypoint: ["/app/chapar-client"]
    restart: unless-stopped
