services:
  chapar-server:
    image: ${GOOSE_SERVER_IMAGE:-ghcr.io/nullroute-lab/chaparcorevpn-server:latest}
    container_name: chapar-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - ./server_config.json:/app/server_config.json:ro
